// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiVRoom.DAL.EF;

#nullable disable

namespace WebApiVRoom.DAL.Migrations
{
    [DbContext(typeof(VRoomContext))]
    [Migration("20241221141051_AddColumnPinnedVideoToChannelSettingsTable")]
    partial class AddColumnPinnedVideoToChannelSettingsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChannelSettings", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            b.Property<string>("ChannelName")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<DateTime>("DateJoined")
                .HasColumnType("datetime2");

            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("ChannelBanner")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("ChannelPlofilePhoto")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("Channel_URL")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("ChannelNikName")
                .HasColumnType("nvarchar(max)");

            b.Property<int>("OwnerId")
                .HasColumnType("int");

            b.Property<int>("LanguageId")
                .HasColumnType("int");

            b.Property<int>("CountryId")
                .HasColumnType("int");

            b.Property<bool>("Notification")
                .HasColumnType("bit");

            b.Property<int>("SubscriptionCount")
                .HasColumnType("int");

            // Добавление нового столбца PinnedVideoId
            b.Property<int?>("PinnedVideoId")
                .HasColumnType("int");

            b.HasKey("Id");

            // Добавление индекса для PinnedVideoId
            // Создание индекса для PinnedVideoId
            b.HasIndex("PinnedVideoId");

            b.ToTable("ChannelSettings");
        });
            //Конфигурация для связи с Video
            modelBuilder.Entity("ChannelSettings")
                .HasOne("PinnedVideo")  // Указываем, что ChannelSettings имеет один PinnedVideo
                .WithMany()  // В зависимости от того, как настроены другие связи в Video
                .HasForeignKey("PinnedVideoId")
                .OnDelete(DeleteBehavior.NoAction);  // Если видео будет удалено, поле PinnedVideoId будет установлено в NULL
            //modelBuilder.Entity("WebApiVRoom.DAL.Entities.ChannelSettings", b =>
            //{
            //    b.HasOne("PinnedVideo")  // Указываем, что ChannelSettings имеет один PinnedVideo
            //    .WithMany()  // В зависимости от того, как настроены другие связи в Video
            //    .HasForeignKey("PinnedVideoId")
            //    .OnDelete(DeleteBehavior.SetNull);  // Если видео будет удалено, поле PinnedVideoId будет установлено в NU

            //    b.Navigation("PinnedVideo");
            //});
#pragma warning restore 612, 618
        }
    }
}